name: CI publish
 
on:
  push:
    branches:
      - master
  schedule:
    - cron: '45 */1 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Generate README.md
      uses: actions-js/profile-readme@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        username: kdy1
        template: "TEMPLATE.md"

      
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        coauthor_email: kdy1@users.noreply.github.com
        coauthor_name: 강동윤
